language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.1
  - 1.2
  - 1.3
dist: xenial
services:
  - xvfb
addons:
  apt:
    packages:
    - libgconf-2-4
matrix:
  allow_failures:
  - julia: 1.3
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
env:
  - PYTHON="" MIMI_RUN_DEPENDENCY_TESTS="TRUE"
codecov: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
