language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Mimi")'
  - julia --check-bounds=yes -e 'Pkg.test("Mimi", coverage=true)'
  - julia -e 'ENV["PYTHON"]=""; Pkg.add("ExcelReaders")'
  - julia -e 'include("test/test_dependencies.jl"); run_dependency_tests()'
after_success:
  - julia -e 'cd(Pkg.dir("Mimi")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("Mimi")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Mimi")); include(joinpath("docs","make.jl"))'
