language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
env:
  - PYTHON=""
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi 
  - $TESTCMD --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Mimi"); Pkg.test("Mimi"; coverage=true)'
#  - julia --check-bounds=yes -e 'include("test/test_dependencies.jl"); run_dependency_tests()'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Mimi")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("Mimi")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'using Pkg; ps=PackageSpec(name="Documenter", version="0.20"); Pkg.add(ps); Pkg.pin(ps)'
  - julia -e 'using Pkg; ENV["DOCUMENTER_DEBUG"]=true; cd(Pkg.dir("Mimi")); include(joinpath("docs","make.jl"))'
