site_name: Mimi.jl
site_url: https://github.com/davidanthoff/Mimi.jl
repo_url: https://github.com/davidanthoff/Mimi.jl
docs_dir: doc
theme: readthedocs
pages:
- Home: index.md
- Tutorial: tutorial.md
- FAQ: faq.md
- Reference: reference.md
- 'Optimization Reference': optimimi.md
